### ISSUE TITLE
Generate test in a big project with dependecies ?

### ISSUE THREAD

**Issue by icyks** [EvoSuite/evosuite#61] opened 2016-11-18 09:13 UTC
Hi,
I want to use your solutions to generate test for a project with a lot of dependecies, but i encouter a lot of problems due to the parent class being in a import by maven. Do you have a solution for this problem ?

Here's the log : 
![capture du 2016-11-18 10-12-37](https://cloud.githubusercontent.com/assets/13676461/20424730/b3943cfa-ad77-11e6-9f4b-653ea4f58a1e.png)

Thank you very much !

**Comment by gofraser** [comment] 2016-11-18 09:18
Is the project you are running EvoSuite on a Maven project, or are there just some dependencies that are Maven projects? Are you using the EvoSuite Maven plugin or running EvoSuite directly on the command line?

**Comment by icyks** [comment] 2016-11-18 09:23
Currently, i'm running EvoSuite directly on the command line because i have some trouble with installing the maven plugin, i think because of some proxies 
And i'm running EvoSuite on a Maven Project, targeting a java class inside this project, which has some dependecies like his parent :
 $EVOSUITE -class fr.gouv.finances.medoc2020.mediamapi.presentation.consultation.commun.AccueilConsultationDonneesMetierControleurPrincipalActivateur -projectCP target/classes

**Comment by gofraser** [comment] 2016-11-18 09:32
Consider using the Maven plugin (http://www.evosuite.org/documentation/maven-plugin/) as this will resolve all your dependencies for you.

If you want to run EvoSuite directly on the command line, you need to make sure that the project classpath is set correctly. As you have dependencies, target/classes is not enough, you also need to include these dependencies. The easiest way to do that on a Maven project would be to call:

mvn dependency:copy-dependencies

This will download all dependencies and place them in target/dependency. You then need to use -projectCP target/classes:target/dependency/foo.jar:target/dependency/bar.jar". Or you could call:

 java -jar evosuite.jar -setup target/class target/dependency/*.jar

This will create an evosuite-files/evosuite.properties with the classpath set, and then you can just omit the "-projectCP" parameter when you invoke EvoSuite to generate tests. However, note that you would need to re-do this every time the Maven dependencies change, so the preferred solution probably is to use the Maven plugin.

I'm closing this because it's not a bug, but let me know if you have more problems.

**Closed by gofraser** 2016-11-18 09:32 UTC
