### ISSUE TITLE
java.net.SocketException: Software caused connection abort: socket write error  at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:158) 

### ISSUE THREAD

**Issue by Pablocgdev** [EvoSuite/evosuite#52] opened 2016-08-26 09:24 UTC
Sometimes (seems like randomly)  evosuite stop generating a test and outputs the following:

[[Progress:==================> 61%] [Cov:=============> 39%][MASTER] 10:35:37.261 [logback-2] ERROR ClientNodeImpl - Cannot inform master of change of state

java.rmi.MarshalException: error marshalling arguments; nested exception is: 
java.net.SocketException: Software caused connection abort: socket write error 
at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:158) ~[na:1.8.0_101] 
at java.rmi.server.RemoteObjectInvocationHandler.invokeRemoteMethod(RemoteObjectInvocationHandler.java:227) ~[na:1.8.0_101]

at java.rmi.server.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:179) ~[na:1.8.0_101] 
at com.sun.proxy.$Proxy9.evosuite_collectStatistics(Unknown Source) ~[na:na] 
at org.evosuite.rmi.service.ClientNodeImpl.updateStatistics(ClientNodeImpl.java:239) ~[evosuite-1.0.3.jar:1.0.3]

at org.evosuite.statistics.StatisticsSender.sendIndividualToMaster(StatisticsSender.java:65) [evosuite-1.0.3.jar:1.0.3]

at org.evosuite.statistics.StatisticsListener$1.run(StatisticsListener.java:71) [evosuite-1.0.3.jar:1.0.3] 
Caused by: java.net.SocketException: Software caused connection abort: socket write error 
at java.net.SocketOutputStream.socketWrite0(Native Method) ~[na:1.8.0_101] 
at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:109) ~[na:1.8.0_101] 
at java.net.SocketOutputStream.write(SocketOutputStream.java:153) ~[na:1.8.0_101] 
at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82) ~[na:1.8.0_101] 
at java.io.BufferedOutputStream.write(BufferedOutputStream.java:126) ~[na:1.8.0_101] 
at java.io.ObjectOutputStream$BlockDataOutputStream.drain(ObjectOutputStream.java:1877) ~[na:1.8.0_101] 
at java.io.ObjectOutputStream$BlockDataOutputStream.setBlockDataMode(ObjectOutputStream.java:1786) ~[na:1.8.0_101]

at java.io.ObjectOutputStream.writeNonProxyDesc(ObjectOutputStream.java:1286) ~[na:1.8.0_101] 
at java.io.ObjectOutputStream.writeClassDesc(ObjectOutputStream.java:1231) ~[na:1.8.0_101] 
at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1427) ~[na:1.8.0_101] 
at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1178) ~[na:1.8.0_101] 
at java.io.ObjectOutputStream.writeFatalException(ObjectOutputStream.java:1577) ~[na:1.8.0_101] 
at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:351) ~[na:1.8.0_101] 
at sun.rmi.server.UnicastRef.marshalValue(UnicastRef.java:294) ~[na:1.8.0_101] 
at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:153) ~[na:1.8.0_101] 
... 6 common frames omitted
](url)

I'm working behind a proxy but the conexions are not rejected/blocked, I've tested this before. I tried scanning with a tool to see what is closing the connection and apparently it is working correctly.

**Comment by gofraser** [comment] 2017-01-03 20:21
EvoSuite relies on an RMI connection between a master and client process. If that connection is closed I am not sure there's much we can do from EvoSuite's point of view. To me this rather looks like a network problem on your side?

**Comment by gofraser** [comment] 2018-04-06 12:05
I have no way of reproducing it, and since there's no updated information I'll close the issue. If the problem persists, please re-open and help us reproduce the problem.

**Closed by gofraser** 2018-04-06 12:05 UTC
