### ISSUE TITLE
TestSuiteGenerator - No Java compiler is available Make sure to run EvoSuite with the JDK and not the JRE.You can try to setup the JAVA_HOME system variable to point to it, as well as to make sure that the PATH variable points to the JDK before any JRE.

### ISSUE THREAD

**Issue by ajmersaini** [EvoSuite/evosuite#74] opened 2017-02-16 13:56 UTC
hello all, i am new to EvoSuite when running the following command 

C:\Tutorial_Stack>java -jar evosuite-1.0.3.jar -class tutorial.Stack

i got the error message 

[MASTER] 20:09:48.081 [logback-2] ERROR TestSuiteGenerator - No Java compiler is available. Make sure to run EvoSuite with the JDK and not the JRE.You can try to setup the JAVA_HOME system variable to point to it, as well as to make sure that the PATH variable points to the JDK before any 

i have tried all possibilities given in above message but in vain. please help

**Comment by gofraser** [comment] 2017-02-17 19:31
This is a duplicate of #73

**Closed by gofraser** 2017-02-17 19:31 UTC
Labels: duplicate
