### ISSUE TITLE
Test case not generated for the private method mentioned in the sample class in PAFM document

### ISSUE THREAD

**Issue by VigneswaranR** [EvoSuite/evosuite#151] opened 2017-11-07 15:36 UTC
Test case not generated for the private method mentioned in the sample class in PAFM document .
http://www.evosuite.org/icst-2017-private-api-access-and-functional-mocking-in-automated-unit-test-generation/

The parameters used while test case generation are :.               
       -Dp_reflection_on_private=0.5
       -Dreflection_start_percent=0.8

Command used - Evosuite:generate

Please let us know if we are missing something since we are unable to generate test cases for private method .

**Comment by gofraser** [comment] 2017-12-14 19:32
I tried this, and I get the tests like described in the paper:

```
  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PAFM2 pAFM2_0 = new PAFM2();
      AnInterface anInterface0 = mock(AnInterface.class, new ViolatedAssumptionAnswer());
      doReturn(true).when(anInterface0).isOK();
      Object object0 = PrivateAccess.callMethod((Class<PAFM2>) PAFM2.class, pAFM2_0, "checkIfOK", (Object) anInterface0, (Class<?>
      assertEquals(true, object0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      PAFM2 pAFM2_0 = new PAFM2();
      AnInterface anInterface0 = mock(AnInterface.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(anInterface0).isOK();
      Object object0 = PrivateAccess.callMethod((Class<PAFM2>) PAFM2.class, pAFM2_0, "checkIfOK", (Object) anInterface0, (Class<?>
      assertEquals(false, object0);
  }
```

This was created using `-Dp_reflection_on_private=0.5 -Dreflection_start_percent=0.8 -Dp_functional_mocking=0.8 -Dfunctional_mocking_percent=0.5`

How did you run EvoSuite, and what was the result?

**Comment by gofraser** [comment] 2018-04-06 10:49
I'll close this issue since it is not reproducible.

**Closed by gofraser** 2018-04-06 10:49 UTC
