### ISSUE TITLE
When method over 120 lines，EvoSuite ended abruptly

### ISSUE THREAD

**Issue by Wanghuayin** [EvoSuite/evosuite#177] opened 2018-03-25 12:12 UTC
### Context
Run the command
`/Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/bin/java  -jar  /Users/xxx/tools/evosuite-1.0.5.jar  -continuous  execute  -Dspawn_process_manager_port=49796  -Dctg_memory=8000  -Dctg_cores=4  -Dctg_time_per_class=30  -Dctg_export_folder=src/evo  -Dctg_selected_cuts=xxx.xxx.ClassName  -DCP_file_path=/var/folders/p4/mvq59qs578961khzhqhwqbxh0000gn/T/EvoSuite_ctg_classpath_file8971499859132395668.txt  `

### Steps to Reproduce
1. Right Click the Class in the intellij
2. Click the evosuite icon
![image](https://user-images.githubusercontent.com/15116717/37874729-280a7202-3067-11e8-975d-03c426559abd.png)
3. Filling the params as below
![image](https://user-images.githubusercontent.com/15116717/37874739-46e316a2-3067-11e8-8920-002349d866e9.png)
4. Click the [OK] button

### Current Result
![image](https://user-images.githubusercontent.com/15116717/37874857-9aad4f80-3069-11e8-9a15-145c63617df1.png)

**Comment by gofraser** [comment] 2018-03-31 13:45
Is the class com.taobao.idlesearch.cs.manager.impl.IdleItemSearchManagerImpl available somewhere so I can try to reproduce this?

**Comment by gofraser** [comment] 2018-04-08 07:28
Actually, the error message in your picture does not seem to be related to the number of lines of code in a method. Can you please provide a minimal example so that I can reproduce this problem?

**Comment by gofraser** [comment] 2018-09-15 08:59
I see you've 'liked' my last question, but is there some way you could help me? Do you have an example where I can reproduce this problem, or can I close this issue since it no longer applies?

**Comment by Wanghuayin** [comment] 2018-09-21 10:02
ok，thank you for your reply,  i will close this issue first, let me study it in depth!

**Closed** 2018-09-21 10:03 UTC
