### ISSUE TITLE
 ERROR ClassStateSupport

### ISSUE THREAD

**Issue by LDily** [EvoSuite/evosuite#86] opened 2017-03-14 12:27 UTC
Thanks.
Edition: evosuite-1.0.4
Command line: java -jar evosuite-1.0.4.jar -class dao.BaseDao -DCP_file_path=jar1.txt -Dtest_naming_strategy=coverage

my test code:
import java.util.ArrayList;
import java.util.List;
import org.hibernate.Query;
import org.hibernate.Session;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
@Repository
public class BaseDao {

	@Autowired
	public HibernateUtil hibernateUtil;

	/**
	 * @param obj
	 *                
	 * @return
	 */
	public boolean add(Object obj) {
		Session session = null;
		// Transaction tran=null;
		boolean result = false;
		try {
			session = hibernateUtil.getSession();
			// tran=session.beginTransaction();
			session.save(obj);
			// tran.commit();
			result = true;
		} catch (Exception e) {
			/*
			 * if(tran!=null) { //     tran.rollback(); }
			 */
		} finally {
			/*
			 * if(session!=null) { //  session session.close(); }
			 */
		}
		return result;
	}

	/**
	 * @return              id  
	 */
	public boolean update(Object object) {
		Session session = null;
		// Transaction tran=null;
		boolean result = false;
		try {
			session = hibernateUtil.getSession();
			// tran=session.beginTransaction();
			session.update(object);
			// tran.commit();
			result = true;
		} catch (Exception e) {
			/*
			 * if(tran!=null){ //     tran.rollback(); }
			 */
		} finally {
			/*
			 * if(session!=null){ //  session session.close(); }
			 */
		}
		return result;
	}

	/**
	 * @param c
	 * @param id
	 *                       id 
	 * @return
	 */
	public Object get(Class c, int id) {
		Session session = null;
		Object object = null;
		try {
			session = hibernateUtil.getSession();
			object = session.get(c, id);
		} catch (Exception e) {
		} finally {
			if (session != null) {
				//   session
				//session.close();
			}
		}
		return object;
	}

	/**
	 * @param obj
	 * @return     
	 */
	public boolean delete(Object obj) {
		Session session = null;
		//Transaction tran = null;
		boolean result = false;
		try {
			session = hibernateUtil.getSession();
			//tran = session.beginTransaction();
			session.delete(obj);
			//tran.commit();
			result = true;
		} catch (Exception e) {
			/*if (tran != null) {
				//     
				tran.rollback();
			}*/
		} finally {
			/*if (session != null) {
				//   session
				session.close();
			}*/
		}
		return result;
	}

	/**
	 * @param <T>
	 *                  
	 * @param sql
	 *            sql  
	 * @param param
	 *                   {"1","2","3"} id 1 2 3     
	 * @return
	 */
	@SuppressWarnings("unchecked")
	public <T> List<T> query(String sql, String[] param) {
		List<T> list = new ArrayList<T>();
		Session session = null;
		try {
			session = hibernateUtil.getSession();
			Query query = session.createQuery(sql);
			if (param != null) {
				for (int i = 0; i < param.length; i++) {
					query.setString(i, param[i]);
				}
			}
			list = query.list();
		} catch (Exception e) {
		} finally {
//			if (session != null) {
//				session.close();
//			}
		}
		return list;
	}

	/**
	 * @param <T>
	 * @param sql
	 * @param param
	 * @param page
	 * @param size
	 * @return       
	 */
	@SuppressWarnings("unchecked")
	public <T> List<T> queryByPage(String sql, String[] param, int page,
			int size) {
		List<T> list = new ArrayList<T>();
		Session session = null;
		try {
			session = hibernateUtil.getSession();
			Query query = session.createQuery(sql);
			if (param != null) {
				for (int i = 0; i < param.length; i++) {
					query.setString(i, param[i]);
				}
			}
			//     
			query.setFirstResult((page - 1) * size);
			query.setMaxResults(size);
			list = query.list();
		} catch (Exception e) {
		} finally {
			/*if (session != null) {
				session.close();
			}*/
		}
		return list;
	}

	/**
	 * @param hql
	 * @param pras
	 * @return      
	 */
	public int getCount(String hql, String[] pras) {
		int resu = 0;
		Session s = null;
		try {
			s = hibernateUtil.getSession();
			Query q = s.createQuery(hql);
			if (pras != null) {
				for (int i = 0; i < pras.length; i++) {
					q.setString(i, pras[i]);
				}
			}
			resu = Integer.valueOf(q.iterate().next().toString());
		} catch (Exception e) {
			e.printStackTrace();
		} finally {
			/*if (s != null)
				s.close();*/
		}
		return resu;
	}

}

[ERROR]:
[MASTER] 20:21:08.551 [logback-2] ERROR TestCluster - Failed to check cache for net.sf.ehcache.config.FactoryConfiguration<T> : Type points to itself

[MASTER] 20:22:37.235 [logback-2] ERROR ClassStateSupport - Could not initialize org.hibernate.id.SelectGenerator: org/hibernate/id/IdentifierGenerationException
[MASTER] 20:22:37.358 [logback-2] ERROR ClassStateSupport - Could not initialize org.hibernate.id.UUIDHexGenerator: org/hibernate/internal/util/BytesHelper
[MASTER] 20:22:37.425 [logback-2] ERROR ClassStateSupport - Could not initialize org.hibernate.id.AbstractUUIDGenerator: Could not initialize class org.hibernate.id.AbstractUUIDGenerator

[MASTER] 20:22:39.420 [logback-2] ERROR ClassStateSupport - Could not initialize org.hibernate.cfg.annotations.EntityBinder: org/hibernate/cfg/annotations/EntityBinder$SecondaryTableNamingStrategyHelper
[MASTER] 20:22:39.606 [logback-2] ERROR ClassStateSupport - Could not initialize org.hibernate.engine.jdbc.spi.SqlExceptionHelper: org/hibernate/exception/internal/SQLStateConverter
[MASTER] 20:22:39.623 [logback-2] ERROR ClassStateSupport - Could not initialize org.hibernate.engine.spi.PersistenceContext$NaturalIdHelper: org/hibernate/engine/spi/PersistenceContext$NaturalIdHelper$1
[MASTER] 20:22:39.638 [logback-2] ERROR ClassStateSupport - Could not initialize net.sf.ehcache.config.TerracottaConfiguration: net/sf/ehcache/config/TimeoutBehaviorConfiguration$TimeoutBehaviorType
[MASTER] 20:22:39.714 [logback-2] ERROR ClassStateSupport - Could not initialize org.hibernate.dialect.Oracle9iDialect: org/hibernate/dialect/Oracle8iDialect$1
[MASTER] 20:22:39.772 [logback-2] ERROR ClassStateSupport - Could not initialize org.hibernate.dialect.HSQLDialect: org/hibernate/dialect/HSQLDialect$1
[MASTER] 20:22:39.813 [logback-2] ERROR ClassStateSupport - Could not initialize oracle.jdbc.driver.OraclePreparedStatement: oracle/jdbc/driver/OraclePreparedStatementReadOnly
[MASTER] 20:22:39.824 [logback-2] ERROR ClassStateSupport - Could not initialize org.hibernate.dialect.PostgreSQL81Dialect: org/hibernate/dialect/PostgreSQL81Dialect$1
[MASTER] 20:22:39.831 [logback-2] ERROR ClassStateSupport - Could not initialize org.hibernate.dialect.InformixDialect: org/hibernate/dialect/InformixDialect$1
[MASTER] 20:22:39.837 [logback-2] ERROR ClassStateSupport - Could not initialize net.sf.ehcache.DiskStorePathManager: net/sf/ehcache/DiskStorePathManager$DiskstoreNotExclusiveException
[MASTER] 20:22:39.854 [logback-2] ERROR ClassStateSupport - Could not initialize org.hibernate.dialect.Oracle10gDialect: org.hibernate.dialect.Oracle9iDialect
[MASTER] 20:22:39.856 [logback-2] ERROR ClassStateSupport - Could not initialize org.hibernate.dialect.ColumnAliasExtractor: org/hibernate/dialect/ColumnAliasExtractor$1
[MASTER] 20:22:39.863 [logback-2] ERROR ClassStateSupport - Could not initialize org.hibernate.cfg.annotations.CollectionBinder: org/hibernate/cfg/annotations/PrimitiveArrayBinder
[MASTER] 20:22:39.870 [logback-2] ERROR ClassStateSupport - Could not initialize org.hibernate.annotations.common.reflection.XClass: org/hibernate/annotations/common/reflection/XClass$1
[MASTER] 20:22:39.879 [logback-2] ERROR ClassStateSupport - Could not initialize org.hibernate.dialect.Oracle8iDialect: Could not initialize class org.hibernate.dialect.Oracle8iDialect
[MASTER] 20:22:39.943 [logback-2] ERROR ClassStateSupport - Could not initialize oracle.jdbc.driver.T2CStatement: oracle/jdbc/driver/T2CNamedTypeAccessor
[MASTER] 20:22:39.959 [logback-2] ERROR ClassStateSupport - Could not initialize org.postgresql.core.Encoding: org/postgresql/core/UTF8Encoding
[MASTER] 20:22:39.965 [logback-2] ERROR ClassStateSupport - Could not initialize oracle.jdbc.driver.OracleTimeout: oracle/jdbc/driver/OracleTimeoutThreadPerVM
[MASTER] 20:22:39.968 [logback-2] ERROR ClassStateSupport - Could not initialize oracle.jdbc.driver.DBConversion: oracle/jdbc/driver/DBConversion$AsciiStream
[MASTER] 20:22:39.979 [logback-2] ERROR ClassStateSupport - Could not initialize net.sf.ehcache.TransactionController: net/sf/ehcache/transaction/TransactionTimeoutException
[MASTER] 20:22:39.984 [logback-2] ERROR ClassStateSupport - Could not initialize org.hibernate.dialect.PostgreSQL82Dialect: org.hibernate.dialect.PostgreSQL81Dialect
[MASTER] 20:22:40.026 [logback-2] ERROR ClassStateSupport - Could not initialize org.hibernate.id.UUIDHexGenerator: Could not initialize class org.hibernate.id.UUIDHexGenerator
[MASTER] 20:22:40.028 [logback-2] ERROR ClassStateSupport - Could not initialize org.hibernate.dialect.H2Dialect: org/hibernate/dialect/H2Dialect$1
[MASTER] 20:22:40.032 [logback-2] ERROR ClassStateSupport - Could not initialize net.sf.ehcache.config.Configuration$DynamicProperty: net/sf/ehcache/config/Configuration$DynamicProperty$1
[MASTER] 20:22:40.036 [logback-2] ERROR ClassStateSupport - Class org.hibernate.engine.jdbc.internal.JdbcServicesImpl$ConnectionProviderJdbcConnectionAccess was not instrumented by EvoSuite. This could happen if you are running JUnit tests in a way that is not handled by EvoSuite, in which some classes are loaded be reflection before the tests are run. Consult the EvoSuite documentation for possible workarounds for this issue.
[MASTER] 20:22:40.036 [logback-2] ERROR ClassStateSupport - Class oracle.jdbc.rowset.OracleCachedRowSet was not instrumented by EvoSuite. This could happen if you are running JUnit tests in a way that is not handled by EvoSuite, in which some classes are loaded be reflection before the tests are run. Consult the EvoSuite documentation for possible workarounds for this issue.
[MASTER] 20:22:40.036 [logback-2] ERROR ClassStateSupport - Class org.hibernate.cfg.annotations.PropertyBinder was not instrumented by EvoSuite. This could happen if you are running JUnit tests in a way that is not handled by EvoSuite, in which some classes are loaded be reflection before the tests are run. Consult the EvoSuite documentation for possible workarounds for this issue.
[MASTER] 20:22:40.036 [logback-2] ERROR ClassStateSupport - Class org.dom4j.tree.DefaultDocumentType was not instrumented by EvoSuite. This could happen if you are running JUnit tests in a way that is not handled by EvoSuite, in which some classes are loaded be reflection before the tests are run. Consult the EvoSuite documentation for possible workarounds for this issue.
[MASTER] 20:22:40.036 [logback-2] ERROR ClassStateSupport - Class org.hibernate.engine.jdbc.internal.JdbcServicesImpl$ExtractedDatabaseMetaDataImpl was not instrumented by EvoSuite. This could happen if you are running JUnit tests in a way that is not handled by EvoSuite, in which some classes are loaded be reflection before the tests are run. Consult the EvoSuite documentation for possible workarounds for this issue.
[MASTER] 20:22:40.036 [logback-2] ERROR ClassStateSupport - Class oracle.jdbc.driver.OracleStatement was not instrumented by EvoSuite. This could happen if you are running JUnit tests in a way that is not handled by EvoSuite, in which some classes are loaded be reflection before the tests are run. Consult the EvoSuite documentation for possible workarounds for this issue.
[MASTER] 20:22:40.036 [logback-2] ERROR ClassStateSupport - Class org.hibernate.ScrollMode was not instrumented by EvoSuite. This could happen if you are running JUnit tests in a way that is not handled by EvoSuite, in which some classes are loaded be reflection before the tests are run. Consult the EvoSuite documentation for possible workarounds for this issue.
[MASTER] 20:22:40.036 [logback-2] ERROR ClassStateSupport - Class org.hibernate.FetchMode was not instrumented by EvoSuite. This could happen if you are running JUnit tests in a way that is not handled by EvoSuite, in which some classes are loaded be reflection before the tests are run. Consult the EvoSuite documentation for possible workarounds for this issue.
...........

**Comment by gofraser** [comment] 2017-03-15 06:22
Could you please list the dependency libraries that are needed to compile your class so I don't need to reverse engineer this? (Or add a pom.xml)

**Comment by LDily** [comment] 2017-03-15 06:35
hibernate-commons-annotations-4.0.1.Final.jar
hibernate-core-4.1.7.Final.jar
hibernate-ehcache-4.1.7.Final.jar
hibernate-jpa-2.0-api-1.0.1.Final.jar
spring-beans-4.1.0.RELEASE.jar
spring-context-4.1.0.RELEASE.jar
spring-context-support-4.1.0.RELEASE.jar

**Comment by gofraser** [comment] 2018-04-06 12:01
I can't reproduce this and am closing this issue. If the problem persists, please provide a fully working minimal example (that doesn't require me to build a new project and learn about web development before I can do any testing...)

**Closed by gofraser** 2018-04-06 12:01 UTC
