### ISSUE TITLE
Getting JPA entitymanager null when running evosuite test case

### ISSUE THREAD

**Issue by AmalGo90** [EvoSuite/evosuite#99] opened 2017-03-27 09:18 UTC
###Issue description:
I have generated evosuite test cases through maven plugin. After I import into eclipse and I ran all the test cases. All were getting passed. Then I had changed mock up data into original test data to see whether my test cases are executing correctly.

I am using JPA entity manager on my DAO. While running the test case I could see entity manager becomes "null".
Can you please assist?

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue.*
1. Generate the test cases
2. Import into eclipse
3. Right and run as junit test

### EvoSuite Arguments
This command i have used for generating test cases.
clean install evosuite:generate evosuite:export test

### Current Result
*Please describe here below the current result you got (if relevant)*
Entity manager becomes null and getting null pointer exception. While debug we could see that mocked objects are "Invocation exception occurred while invoking the method. Please explain on this.
 
### Expected result
By running evosuite test cases expected that it should interact with the database and get the results with the original test data.

**Comment by AmalGo90** [comment] 2017-03-29 06:58
Hi team, 
 Can you please help to provide solution?

**Comment by karthikjeyapal** [comment] 2017-03-29 07:05
even i'm also faced same issues please kindly provide your suggestion

**Comment by sinaa** [comment] 2017-03-29 08:40
Can you please provide an example project package so that we can replicate your problem? With the existing information provided, there's no way for us to replicate your issue and to investigate it.

**Comment by AmalGo90** [comment] 2017-03-29 09:44
Thanks Sinaa for your reply. Please look into below sample code.

persistence.xml kept under src/test/resources
--------------------------------------------
<?xml version="1.0" encoding="UTF-8"?>
<persistence xmlns="http://xmlns.jcp.org/xml/ns/persistence"
             xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence
             http://xmlns.jcp.org/xml/ns/persistence/persistence_2_1.xsd"
             version="2.1">
  <persistence-unit name="storeaudit" transaction-type="JTA">
    <provider>org.hibernate.jpa.HibernatePersistenceProvider</provider>

    
    <jta-data-source>java:openejb/Resource/auditDataSource</jta-data-source>

    <class>com.example.Audit</class>
	
	 </persistence-unit>
</persistence>


DataRepository.java
-------------------
import java.util.Collection;
import java.util.List;
import javax.ejb.Stateless;
import javax.ejb.TransactionAttribute;
import javax.ejb.TransactionAttributeType;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaDelete;
import javax.persistence.criteria.CriteriaQuery;

@Stateless
public class DataRepository
{
@PersistenceContext(name="storeaudit")
	protected EntityManager em;
	
	public CriteriaBuilder criteriaBuilder()
	{
	   return em.getCriteriaBuilder();
	}
	
	public <T> List<T> search(CriteriaQuery<T> query)
	{
	   return this.em.createQuery(query).getResultList();
	}
}


AuditService_ESTest.java
@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true)
public class AuditService_ESTest extends AuditService_ESTest_scaffolding {
	
 List<NegatedPredicateWrapper> list0 = (List<NegatedPredicateWrapper>) mock(List.class, new ViolatedAssumptionAnswer());
      DataRepository dataRepository0 = mock(DataRepository.class, new ViolatedAssumptionAnswer());
      doReturn(criteriaBuilder0).when(dataRepository0).criteriaBuilder();
      System.out.println("Before search" + entityManager);
      doReturn(list0).when(dataRepository0).search(any(javax.persistence.criteria.CriteriaQuery.class));
}

While debugging above test case i will call the search method written in DataRepository to fetch data from DB. When i inspect the entity manager 
I could see "com.sun.jdi.InvocationException occurred invoking method" error. Please explain on when this exception would come and what case. Please let us know if you need more info.

**Comment by sinaa** [comment] 2017-03-29 09:48
Can you please provide the full stack trace of the error? this is an error you are getting when running the generated evosuite test?

**Comment by AmalGo90** [comment] 2017-03-29 10:03
It's not throwing exception, but it's showing the above high lighted error when i inspect the object. Can you please confirm for the below also.

 While run the test case it should load persistence.xml? or separate configuration required to load the persistence.xml?

**Comment by AmalGo90** [comment] 2017-03-30 04:54
could you please update?

**Comment by karthikjeyapal** [comment] 2017-03-30 04:58
sinna- kindly provide your suggestions , Thanks in Advance

**Comment by AmalGo90** [comment] 2017-03-31 04:36
Hi Sina,

can you please share an update?

**Comment by gofraser** [comment] 2017-03-31 07:46
Can you please provide a pom.xml to build your example, so we don't have to reverse engineer everything here.

**Comment by gofraser** [comment] 2018-04-06 11:55
Since I still don't have a reproducible example, I'm going to close this issue. If the problem persists, please re-open the issue and provide a fully reproducible example.

**Closed by gofraser** 2018-04-06 11:55 UTC
