### ISSUE TITLE
ERROR AbstractStatement

### ISSUE THREAD

**Issue by LDily** [EvoSuite/evosuite#92] opened 2017-03-20 03:26 UTC
Thanks. I got an error for a class and I can't undersand what mean of the error. It may come from jdk?

ERROR AbstractStatement - Error assigning value of type TemporalQuery[] defined at statement TemporalQuery<MockThaiBuddhistDate>[] temporalQueryArray0 = (TemporalQuery<MockThaiBuddhistDate>[]) Array.newInstance(TemporalQuery.class, 2);, assignment statement: temporalQueryArray0[0] = (TemporalQuery<MockThaiBuddhistDate>) temporalQueryArray0;; SUT=smp.controller.MetrController

**Comment by gofraser** [comment] 2017-03-31 07:51
It looks like something went wrong internally in EvoSuite during test generation. However, the particular test with that problem should simply have been discarded during the search so you should still have received a regular test suite. Did that happen, or did EvoSuite crash?

**Comment by LDily** [comment] 2017-03-31 07:58
I still have received a test suite,but I'm not sure if this problem have an influence for test generation.

**Comment by gofraser** [comment] 2017-03-31 08:00
It should make no difference. 

What class/project did you run EvoSuite on when you got this problem?

**Comment by LDily** [comment] 2017-03-31 08:03
A project for SpringMVC 
A controller class

**Comment by gofraser** [comment] 2018-04-06 11:57
I assume this is just an error message but did not crash EvoSuite. Since I can't reproduce it there's not much I can do, so I'll close this issue for now.

**Closed by gofraser** 2018-04-06 11:57 UTC
Labels: bug
