### ISSUE TITLE
EvoSuite Test behaves differently depending the execution context (v1.0.5)

### ISSUE THREAD

**Issue by JavaJimFl** [EvoSuite/evosuite#127] opened 2017-07-18 20:46 UTC
### Context
I have an EvoSuite-generated test that behaves differently when invoked in an IDE than when executed using Maven from the command-line:

```Java
    @Test(timeout = 4000)
    public void testDoValidation()  throws Throwable  {
        Foo foo0 = new Foo();
        foo0.setZoneKey("");
        ValidationContainer validationContainer0 = new ValidationContainer();
        foo0.doValidation(validationContainer0);
        assertEquals(5, validationContainer0.size());
        assertEquals(5, validationContainer0.getErrorCount());
    }
```

The expectation for the validation message and error counts was generated by EvoSuite.  When invoked from within an IDE, it works, but fails during a maven build, which only shows four validation messages, not five.  I debugged the test in the IDE and found a ```isNumeric``` validation call that takes a ```Number``` as a parameter.  In this case, the validation candidate is a ```BigDecimal```.  This validation call invokes an overloaded method that in turn calls the ```toString()``` method of the candidate.  I can see the value is a single digit ("0") in the debugger at this point.  However, when this string is forwarded as a parameter to a more generic validation method (via some EvoSuite runtime methods), it changes to "java.math.BigDecimal@0000000012", which is not a number, and the reason for fifth validation error.  Since the expectation was set for five errors, the test passes.

I added logging to the test before running it as part of a Maven build, and the numeric validation error wasn't generated.  The test fails with the message "expected:<5> but was:<4>."

I also took the entire test method, pasted it unchanged into a test class in the ```src/test/java``` folder, and it fails with the same message, "expected:<5> but was:<4>."

### EvoSuite Arguments
java -jar c:\\evosuite\\evosuite-master-1.0.5.jar -generateTests -class foo.class

 
### Expected result
I would expect the test to behave the same way in any typical JUnit execution context (IDE, Maven, command-line).

### Additional info
When I generated the test, the "use_separate_classloader" property was defaulted to "true"  I manually removed the "separateClassLoader" attribute of the  "EvoRunnerParameters" annotation from the generated class so I could see code coverage metrics using JaCoCo.

**Comment by gofraser** [comment] 2018-04-06 17:04
Is the ValidationContainer class available somewhere, or could you produce a minimised version for debugging? It's not clear to me whether the toString() (that seems to invoke Object.toString()) is regular behaviour or not. If it is regular behaviour then this is flaky behaviour that'll be difficult to avoid - for example, the length of Object.toString() can differ in different runs. But if that conversion to a string is wrong and caused by EvoSuite then that should be fixed. But I have no means of finding this out without the class under test.

**Comment by JavaJimFl** [comment] 2018-04-11 22:27
It's proprietary, so I can't share it.  I deleted the flaky tests, and haven't generated them again since.

**Comment by gofraser** [comment] 2018-04-16 19:12
Right, thanks. I don't have anything concrete to test/fix here, so I'll close the issue. If there is a specific example of a flaky test that EvoSuite produces, if you can identify which code produces the flakiness we can try to extend EvoSuite's mocking framework to replace the nondeterministic calls. 

In this case it seems like the issue is that hashCodes are non-deterministic, and I am not sure that's an issue we're ever going to be able to fix...

**Closed by gofraser** 2018-04-16 19:12 UTC

**Comment by JavaJimFl** [comment] 2018-04-16 21:17
That's quite possible. The objects in question don't override equals/hashcode.
