### ISSUE TITLE
Evosuite not generating test case for DAO package

### ISSUE THREAD

**Issue by AmalGo90** [EvoSuite/evosuite#102] opened 2017-03-29 11:01 UTC
### Context
I am trying to generate the test case for DAO package but its not getting generated. Seems while generating test case for the BaseDaoSupport it gives me following error. Due to that wherever I extends this BaseDaoSupport that classes also not getting generated.

[INFO] [MASTER] 16:25:31.746 [main] WARN  StorageManager - No CSV file for CUT  with test suite at C:\TestSpringBoot\.evosuite\tmp_2017_03_29_16_15_53\tests\com\wal\acc\dao\impl\BaseDaoSupport_ESTest.java

Can you please assist?

### Steps to Reproduce
1. run this evosuite  maven plugin goal to generate test case.

### EvoSuite Arguments
clean evosuite:generate evosuite:export test

### Expected result
It should generate the test case for the DAO pacakage

### Additional info
Please look the below code and provide solution

pom.xml
----------
<profile>
			<id>junitgeneration</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.springframework.boot</groupId>
						<artifactId>spring-boot-maven-plugin</artifactId>
					</plugin>
					<plugin>
						<groupId>org.codehaus.sonar</groupId>
						<artifactId>sonar-maven-plugin</artifactId>
						<version>4.5.1</version>
					</plugin>
					<plugin>
						<groupId>org.evosuite.plugins</groupId>
						<artifactId>evosuite-maven-plugin</artifactId>
						<version>1.0.4-alpha1</version>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-surefire-plugin</artifactId>
						<version>2.17</version>
						<configuration>
							<properties>
								<property>
									<name>listener</name>
									<value>org.evosuite.runtime.InitializingListener</value>
								</property>
							</properties>
						</configuration>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-compiler-plugin</artifactId>
						<configuration>
							<excludes>
								<exclude>**/model/*.java</exclude>
							</excludes>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>

BaseDaoSupport .java
-----------------
package com.wal.acc.dao.impl;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.jpa.HibernateEntityManagerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.jdbc.core.JdbcTemplate;

public class BaseDaoSupport {

	@Autowired
	private JdbcTemplate jdbcTemplate;

	@Autowired
	private SessionFactory sessionFactory;

	@Bean
	public SessionFactory sessionFactory(HibernateEntityManagerFactory hemf) {
		return hemf.getSessionFactory();
	}

	public Session getSession() {
		Session session = sessionFactory.getCurrentSession();
		return session;
	}

	public JdbcTemplate getJdbcTemplate() {
		return jdbcTemplate;
	}

	public void setJdbcTemplate(JdbcTemplate jdbcTemplate) {
		this.jdbcTemplate = jdbcTemplate;
	}
}

SpringBootDaoImpl.java
--------------------------
package com.wal.acc.dao.impl;
import com.wal.acc.dao.api.SpringBootDao;
import java.util.*;
import java.util.logging.Logger;
import org.hibernate.Criteria;
import org.springframework.stereotype.Repository;
import com.wal.acc.dto.jaxb.*;
import com.wal.acc.common.DAOException;
import com.wal.acc.dao.impl.BaseDaoSupport;
import com.wal.acc.model.Automation;

@Repository
public class SpringBootDaoImpl extends BaseDaoSupport implements SpringBootDao {

	private static final Logger logger = Logger
			.getLogger(SpringBootDaoImpl.class.getName());

	@Override
	public String getBoot(RequestVO requestVO) throws DAOException {
		logger.info("dao getBoot started");
		Criteria criteria = getSession().createCriteria(Automation.class);
		//criteria.add(Restrictions.eq("id", requestVO.getId()));
		List<Automation> id = criteria.list();
		String a = null;
		for(Automation automation : id){
			a = automation.getText();
		}
		return a;
	}

	@Override
	public List<String> getBootSpring(RequestVO requestVO) throws DAOException {
		logger.info("dao getBootSpring started");
		List<String> list = new ArrayList<String>();
		list.add(requestVO.getId());
		Automation automation = new Automation();
		automation.setId((short) 22);
		automation.setText("am"+requestVO.getId());
		getSession().save(automation);		
		return list;
	}
}

If I remove "extends BaseDaoSupport " from my DAO impl, test case getting generated. But after adding, test case not getting generated. Please assist.

**Comment by AmalGo90** [comment] 2017-03-30 04:55
could you please update?

**Comment by karthikjeyapal** [comment] 2017-03-30 05:01
same issues only i'm facing please provide suggestions

**Comment by AmalGo90** [comment] 2017-03-31 04:36
Hi Sina,

can you please share an update?

**Comment by gofraser** [comment] 2017-03-31 07:36
Asking every couple of hours will not get this problem solved quicker.

Can you please provide a complete pom.xml rather than an excerpt so that we can build your example.

**Comment by gofraser** [comment] 2017-04-17 15:19
@AmalGo90 if you want me to fix this, can you please produce a minimal example. I cannot run your source code example because I don't know what the dependencies are, and I don't have all dependencies that are imported. (Same holds for #99)

**Comment by gofraser** [comment] 2018-04-06 11:54
Since I cannot reproduce this, I am closing this issue.

**Closed by gofraser** 2018-04-06 11:54 UTC

**Comment by dilagurung** [comment] 2020-10-01 17:37
getting the same issue
