### ISSUE TITLE
generated Testcase not covering all the path and branches of a method

### ISSUE THREAD

**Issue by VigneswaranR** [EvoSuite/evosuite#149] opened 2017-11-06 10:43 UTC
### Context
*Please provide below a detailed introduction to the issue itself, and describe what you were doing when the issue happened. Or, what do you want to achieve?*

Evosuite is used to generate testcase .  We noticed following:
1) Only exception case is covered. therefore all the branches and paths in the method is not covered.
2) Mock for all the objects inside the method is not happening. i.e mocking of the functional objects is not happening.

Please let us know if we are missing any evosuite argument to be given

We are expecting EvoSuite to create test cases with which min 65% of the code is covered . And the cases other than exception case is also considered while  generating test case.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue.*
[If possible, please upload an example of the project you are generating tests for.]

We are running "evosuite:generate" command in eclipse with the below mentioned evosuite parameters.
1. -DcutsFile=c:\temp\cutsFile.txt  -Dp_reflection_on_private=1 -Dp_functional_mocking=1

### EvoSuite Arguments
*Please provide the whole EvoSuite commmand you executed (if relevant)*

We ran test cases with below mentione set of Arguments :
1. -DcutsFile=c:\temp\cutsFile.txt  -Dp_reflection_on_private=1 -Dp_functional_mocking=1

### Current Result
*Please describe here below the current result you got (if relevant)*
[if relevant, include a screenshot]

We are unable to see that all the path in the method covered.
 
### Expected result
*Please describe here below what should be the expected behaviour (if relevant)*

Evosuite generated Test cases sholud cover all the path in the method. 
Please let us know if we are missing any evosuite argument to be given

### Additional info
*Please add any information of interest here below*

**Comment by mohanachelvi** [comment] 2017-11-06 11:08
Do we need to explicitly enable PAFM capability of Evosuite?  

1) My CUT has a private method and  the generated  test class does not create test case for the private methods. 
2) Also, my CUT has a public method which calls objects of other classes and does some logic check. The generated test class had test cases which just covered the exception part of this public method and the functional/busniess logic was just skipped.

Am I Missing something here? PAFM document clearly says private methods can be invoked from test case and functional mocking is also captured as part of evosuite. But when I generate, it is not getting covered. Tried with the below  arguments and its different combination is also tried. Can you please help on this?

-Dlog.level=trace -Dsearch_budget=500 -Dp_reflection_on_private=0.0 -Dreflection_start_percent=1.0 -Dp_functional_mocking=0.0 -Dfunctional_mocking_percent=1.0

**Comment by VasamGH** [comment] 2017-12-01 05:20
We are also facing the same issue, the test cases generated by EvoSuite is not covering the branches/instructions, let us know in case if we are missing any params/args.?

**Comment by gofraser** [comment] 2017-12-01 07:01
EvoSuite cannot guarantee that all branches are covered. In the example given above, if a branch depends on some complex dependency objects, and if EvoSuite fails to generate the necessary instances of these dependency objects, you may just get coverage of exceptional cases. In most cases this is just a limitation of the approach, but if you think there's something wrong here, then an example to reproduce the behaviour would be useful.

Btw, this:
-Dp_reflection_on_private=0.0 -Dreflection_start_percent=1.0 -Dp_functional_mocking=0.0 -Dfunctional_mocking_percent=1.0
...turns off reflection/mocking (and it is off by default). To turn it on you would need to set the start_percent to something < 1, and the p_* to something > 0.

**Comment by VigneswaranR** [comment] 2017-12-01 07:20
Test case not generated for the private method mentioned in the sample class in PAFM document .
http://www.evosuite.org/icst-2017-private-api-access-and-functional-mocking-in-automated-unit-test-generation/

The parameters used while test case generation are :.
-Dp_reflection_on_private=0.5
-Dreflection_start_percent=0.8

Command used - Evosuite:generate

Please let us know if we are missing something

**Comment by mohanachelvi** [comment] 2017-12-01 07:22
@gofraser we got to know that values 1.0 would turn off the feature from the PAFM document and we were currently using the optimal values suggested in the document i.e. 
-Dp_reflection_on_private=0.5 -Dreflection_start_percent=0.8 -Dp_functional_mocking=0.8 -Dfunctional_mocking_percent=0.5
Now for few CUTs private methods are covered and is not same case for all CUTs with private methods. Functional mocking of collaborators objects is not getting covered even with optimal values.

**Comment by gofraser** [comment] 2017-12-14 19:37
I am not sure I understand what you are trying to say. Why is the "get = new GetMethod(url)" highlighted, and what's special about that? What would you like to have covered?

**Comment by gofraser** [comment] 2018-04-06 10:50
Closing this issue since there's not enough information to reproduce it.

**Closed by gofraser** 2018-04-06 10:50 UTC
