### ISSUE TITLE
error: cannot assign a value to final variable def

### ISSUE THREAD

**Issue by yevsh** [EvoSuite/evosuite#65] opened 2016-12-14 11:33 UTC
Evosuite generated tests, but some test like:

```
  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Msg.def = null;
      // Undeclared exception!
      try { 
      .
      .
      .
```
Msg.def  is a a public static type!

So getting an error 
error: cannot assign a value to final variable def

**Comment by gofraser** [comment] 2017-01-03 20:17
Can I access this class Msg somewhere?

**Comment by yevsh** [comment] 2017-01-04 07:21
What do you mean access somewhere?

It's s simple calss, and 'def' is
 public static final DynamicMsg def = new DynamiclMsg(<some constant>);

**Comment by gofraser** [comment] 2017-01-04 08:39
I mean where can I find the class Msg to reproduce this. I've tried something like the following but cannot reproduce the behaviour you described (tried version 1.0.2 upwards):

public class StaticFinalAssignment {

    public static final String FOO = "foo";

    public boolean testMe() {
        if(FOO.equals("foo"))
            return true;
        else
            return false;
    }
}

**Comment by gofraser** [comment] 2017-01-06 01:09
If the Msg class is not something you can share, could you maybe reproduce a minimal example class that also exhibits this behaviour so I could look at this?

**Comment by gofraser** [comment] 2017-02-17 19:38
If you cannot help me to reproduce this problem, I will close this issue. For all I've tried it seems to be working ok.

**Closed** 2018-04-06 11:57 UTC
