### ISSUE TITLE
Does evosuite support Scala test ?

### ISSUE THREAD

**Issue by joeyzywang** [EvoSuite/evosuite#30] opened 2016-05-17 16:56 UTC
I tried to use evosuite in Scala testing. But it seems failed.
The source code is an object, and defined some public def (function).
No tests generated success even. 

Am I doing something wrong, or we really not support Scala yet ?

**Comment by joeyzywang** [comment] 2016-05-17 17:26
More info may help are below.


```
MASTER] 12:23:42.306 [logback-2] ERROR TestSuiteGenerator - Problem for com.joeywang.scala.App. Full stack:
java.lang.StringIndexOutOfBoundsException: String index out of range: 23
	at java.lang.String.charAt(String.java:646) ~[na:1.8.0_05]
	at org.evosuite.setup.TestClusterUtils.isAnonymousClass(TestClusterUtils.java:95) ~[evosuite-1.0.3.jar:1.0.3]
	at org.evosuite.setup.TestUsageChecker.canUse(TestUsageChecker.java:187) ~[evosuite-1.0.3.jar:1.0.3]
	at org.evosuite.setup.TestClusterGenerator.initializeTargetMethods(TestClusterGenerator.java:621) ~[evosuite-1.0.3.jar:1.0.3]
	at org.evosuite.setup.TestClusterGenerator.generateCluster(TestClusterGenerator.java:135) ~[evosuite-1.0.3.jar:1.0.3]
	at org.evosuite.setup.DependencyAnalysis.analyze(DependencyAnalysis.java:117) ~[evosuite-1.0.3.jar:1.0.3]
	at org.evosuite.setup.DependencyAnalysis.analyzeClass(DependencyAnalysis.java:131) ~[evosuite-1.0.3.jar:1.0.3]
	at org.evosuite.TestSuiteGenerator.generateTestSuite(TestSuiteGenerator.java:110) ~[evosuite-1.0.3.jar:1.0.3]
	at org.evosuite.rmi.service.ClientNodeImpl$1.run(ClientNodeImpl.java:145) [evosuite-1.0.3.jar:1.0.3]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_05]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_05]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_05]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_05]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_05]
* Computation finished
```

**Comment by joeyzywang** [comment] 2016-05-17 19:42
[jars.zip](https://github.com/EvoSuite/evosuite/files/269005/jars.zip)

```
java -jar evosuite-1.0.3.jar -generateTestcases -target scalaArchetype-1.0-SNAPSHOT.jar –projectCP scala-lib-2.11.5.jar
```

**Comment by arcuri82** [comment] 2016-05-19 15:50
Hi,
  EvoSuite works at the bytecode level. So it does not matter the source language (Java, Scala, Kotlin, etc), although the output tests will be in Java Junit 4. It does not seem you did anything wrong, as it looks like just a bug. Thanks for providing the jars.zip, so I can try to reproduce it

cheers

Andrea

**Comment by gofraser** [comment] 2018-04-06 17:50
This must be a duplicate of #179 which has been fixed, so I am closing this.

**Closed by gofraser** 2018-04-06 17:50 UTC
Labels: bug
