### ISSUE TITLE
Evosuite didn't generate any test case

### ISSUE THREAD

**Issue by LDily** [EvoSuite/evosuite#85] opened 2017-03-14 12:06 UTC
Thanks.
I used the evosuite-1.0.4 in command line.
java -jar evosuite-1.0.4.jar -class controller.treeController.TreeController -DCP_file_path=jar1.txt  -Dtest_naming_strategy=coverage

the test code:
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.servlet.http.HttpServletRequest;
import org.apache.commons.lang.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller
@RequestMapping("/tree")
public class TreeController {
	
	@Autowired
	private TreeService treeService;
	
	@RequestMapping(value = "/geDepTree")
	@ResponseBody
	public List<Map<String, Object>> geDepTree(
			@RequestParam(value = "depId", required = false) String depId,
			HttpServletRequest request, Model model) {
		
		SecurityBean operator = (SecurityBean) request.getSession().getAttribute("operator");
		/*List<DepartMent> subDeptList = new ArrayList<DepartMent>();
		subDeptList = (List<DepartMent>) request.getSession().getAttribute("subDeptList");*/
		
		List<Map<String, Object>> list = new ArrayList<Map<String,Object>>();
		
		/*       */
		if(StringUtils.isBlank(depId)){
			/*      */
			//List<DepartMent> depList = treeService.queryDepTree();
			DepartMent departMent = operator.getDepartMent();
			List<DepartMent> subDepList = treeService.querySubDepList(departMent.getId());
			
			Map<String, Object> node = new HashMap<String, Object>();
			node.put("id", departMent.getId());
			node.put("name", departMent.getName());
			node.put("isParent", subDepList.isEmpty()?false:true);
			node.put("hasChild", subDepList.isEmpty()?false:true);
			//        
			node.put("nocheck", false);
			node.put("pId", "N");
			node.put("open", true);
			node.put("icon", subDepList.isEmpty()?"":request.getContextPath()+"/commons/Image/zTreeStyle/folderClosed.gif");
			list.add(node);
		}
		
		if(StringUtils.isNotBlank(depId)){
			List<DepartMent> subDepList = new ArrayList<DepartMent>();
			subDepList = treeService.querySubDepList(depId);
			
			for(DepartMent subDep:subDepList){
				/*       */
				List<DepartMent> departMents = treeService.querySubDepList(subDep.getId());
				
				Map<String, Object> node = new HashMap<String, Object>();
				node.put("id", String.valueOf(subDep.getId()));
				node.put("pId", depId);
				node.put("icon", departMents.isEmpty()?"":request.getContextPath()+"/commons/Image/zTreeStyle/folderClosed.gif");
				node.put("name", subDep.getName());
				node.put("nocheck", false);
				node.put("hasChild", departMents.isEmpty()?false:true);
				node.put("isParent", departMents.isEmpty()?false:true);
				node.put("open", true);
				list.add(node);
			}
			
		}
		
		return list;
	}
	
}

**Comment by gofraser** [comment] 2017-03-15 06:19
Could you please list the dependency libraries that are needed to compile your class so I don't need to reverse engineer this? (Or add a pom.xml)

**Comment by LDily** [comment] 2017-03-15 06:32
It contains these dependency libraries:
javax.servlet-3.0.1.jar
commons-lang-2.6.jar
spring-beans-4.1.0.RELEASE.jar
spring-web-4.1.0.RELEASE.jar
spring-context-4.1.0.RELEASE.jar
spring-context-support-4.1.0.RELEASE.jar

**Comment by LDily** [comment] 2017-03-15 07:29
I want to use evosuite-maven-plugin for edition 1.0.4, where can I download it ? Thank you !

**Comment by gofraser** [comment] 2017-03-15 07:31
The EvoSuite Maven plugin and dependencies are all on Maven Central.

**Comment by LDily** [comment] 2017-03-15 07:32
OK ,thank you .

**Comment by LDily** [comment] 2017-03-15 09:09
Hello ,can Evosuite Maven Plugin generates test suite using options like command line such as “-prefix” and "-Dxxx"?  
If can ,how to use?
thank you

**Comment by gofraser** [comment] 2018-04-06 11:59
This doesn't seem to be a bug per se, it may just be a limitation of what EvoSuite can test currently. I cannot reproduce this, so I am closing this for now.

**Closed by gofraser** 2018-04-06 11:59 UTC
