### ISSUE TITLE
How to cover more test scenarios?

### ISSUE THREAD

**Issue by eversonalcantara** [EvoSuite/evosuite#224] opened 2018-08-31 18:15 UTC
We are using evosuite in one of our projects, but we have noticed that in the generation of tests we are testing less scenarios than expected.

For example:
Evosuite generates the scenarios:
> setNumberSheet("X,n)q[l.Gg");
> setNumberSheet("");
> setDesMotivoAnulacion("");
> setCodUser("r a/Gd*P/<7(x_a+ 0");
> setCodCliente("");
> setCodChannel("&Ka");
> setCodChannel("");
> setCodClienteEmisor(")*lJAh:");
> setCodUsuarioSolicitante("");

and we would like to have the following scenarios for a single method:

> setNumberSheet("X,n)q[l.Gg");
> setNumberSheet("");
> setNumberSheet(nulll);
> setNumberSheet(new ObjectXPTO());
> setNumberSheet("STRING TOO LARGE");

I would like to know how we can adjust evosuite so that it manages a greater amount of scenarios?

**Comment by gofraser** [comment] 2018-09-09 12:49
I'm afraid this is not something that can be explicitly set: EvoSuite optimises tests for code coverage, so there would need to be some hint in the code to make it produce additional scenarios for your setNumberSheet method (e.g. if-conditions checking other properties of the input parameters, such as checks for null values etc). 

You could deactivate minimisation (-Dminimize=false) to avoid that tests are minimized with respect to coverage and *might* get some additional invocations of your methods.

I'm closing this issue since it's not a bug, but let me know if you need more information.

**Closed by gofraser** 2018-09-09 12:49 UTC
